# Analysis of longitudinal data (Exercise 6)
Read data
```{r}
BPRS<-read.table("https://raw.githubusercontent.com/KimmoVehkalahti/MABS/master/Examples/data/BPRS.txt", sep=" ", header=TRUE)
RATS<- read.table("https://raw.githubusercontent.com/KimmoVehkalahti/MABS/master/Examples/data/rats.txt", sep="\t", header=TRUE)
library(ggplot2);library(dplyr);library(tidyr)
```
## Task 1

Convert catergorial variables in RATS dataset to factors and to long form
```{r}
RATS$Group<-factor(RATS$Group)
RATS$ID<-factor(RATS$ID)
glimpse(RATS)
head(RATS)
RATSL<-gather(RATS, key=WDs, value=weight, WD1:WD64)%>%mutate(time= as.integer(substr(WDs,3,4)))
glimpse(RATSL)
head(RATSL)
tail(RATSL)
```

## Task 1
```{r}
ggplot(RATSL, aes(x = time, y = weight, linetype = ID)) +
  geom_line() +
  scale_linetype_manual(values = rep(1:10, times=4)) +
  facet_grid(. ~ Group, labeller = label_both) +
  theme(legend.position = "none") + 
  scale_y_continuous(limits = c(min(RATSL$weight), max(RATSL$weight)))
```
Standardise the weight
```{r}
RATSL<- RATSL%>%group_by(time)%>%mutate(stdweight = (weight - mean(weight))/sd(weight))%>%ungroup()
glimpse(RATSL)
```
```{r}
p1<-ggplot(RATSL, aes(x=time, y=stdweight, linetype=ID))
p2<-p1+geom_line()+scale_linetype_manual(values=rep(1:10, times=4))
p3<-p2+facet_grid(. ~Group, labeller = label_both)
p4<-p3+theme_bw()+theme(legend.position ="none")
p5<-p4+theme(panel.grid.minor.y=element_blank())
p6<-p5+scale_y_continuous(name="standardized weights")
p6
```

Numberof times, baseline (time 0)
```{r}
n<-RATSL$time%>%unique()%>%length()
```
Make a summary data
```{r}
RATSS<-RATSL%>%group_by(Group, time)%>% summarise(mean=mean(weight), se=sd(weight)/sqrt(n))%>%ungroup()
glimpse(RATSS)
```
Visualize the  mean weight and SE
```{r}
p1<-ggplot(RATSS, aes(x=time, y=mean, linetype=Group, shape=Group))
p2<-p1+geom_line()+scale_linetype_manual(values=c(1,2,3))
p3<-p2+geom_point(size=3)+scale_shape_manual(values=c(1,2,3))
p4<-p3+geom_errorbar(aes(ymin=mean-se, ymax=mean+se, linetype="1"), width=0.3)
p5<-p4+theme_bw()+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank())
p6<-p5+theme(legend.position= "top")
p7<-p6+scale_y_continuous(name="mean(weights) +/- se(weights)")
p7

```

## Task 2

```{r}
BPRS$treatment<-factor(BPRS$treatment)
BPRS$subject<-factor(BPRS$subject)
str(BPRS)
BPRSL<-gather(BPRS, key=weeks, value=bprs, -treatment, -subject)%>%mutate(week=as.integer(substr(weeks, 5, 5)))
glimpse(BPRSL)
head(BPRSL)
tail(BPRSL)
```

```{r}
p1<-ggplot(BPRSL, aes(x=week, y=bprs, group=subject))
p2<-p1+geom_text(aes(label=treatment))
p3<-p2+scale_x_continuous(name = "Time(weeks)", breaks = seq(0,8,2))
p4<-p3+scale_y_continuous(name="bprs")
p5<-p4+theme_bw()
p6<-p5+theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank())
p6
```

```{r}
BPRS_reg<-lm(bprs ~ week + treatment, data=BPRSL)
summary(BPRS_reg)
```

```{r}
p1<-ggplot(BPRSL, aes(x=week, y=bprs, group=subject))
p2<-p1+geom_line(aes(linetype=treatment))+geom_point()+scale_linetype_manual(values=c("twodash", "dotted"))
p3<-p2+scale_x_continuous(name="time(weeks)")
p4<-p3+scale_y_continuous(name="bprs")
p5<-p4+theme_bw()+theme(legend.position= "top")
p6<-p5+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank())
p6
```

```{r}
library(lme4)
BPRS_ref<-lmer(bprs ~ week + treatment + (1|subject), data=BPRSL, REML=F)
summary(BPRS_ref)
```
```{r}
BPRS_ref1<-lmer(bprs~week+treatment+(week|subject), data=BPRSL, REML=F)
summary(BPRS_ref1)
```
```{r}
anova(BPRS_ref1, BPRS_ref)
```

```{r}
BPRS_ref2<-lmer(bprs~week+treatment+(treatment|subject), data=BPRSL, REML=F)
summary(BPRS_ref2)
```
```{r}
anova(BPRS_ref1, BPRS_ref2)
```

```{r}
Fitted<-fitted(BPRS_ref2)
BPRSL%>% mutate(Fitted)
```

```{r}
p1<-ggplot(BPRSL, aes(x=week, y=bprs, group=subject))
p2<-p1+geom_line(aes(linetype=treatment,))
p3<-p2+scale_x_continuous(name="Time(weeks)", breaks = seq(0,8,2))
p4<-p3+scale_y_continuous(name = "bprs")
p5<-p4+theme_bw()+theme(legend.position="right")
p6<-p5+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank())
p7<-p6+ggtitle("Observed")
graph1<-p7
p1<-ggplot(BPRSL, aes(x=week, y=Fitted, group=subject))
p2<-p1+geom_line(aes(linetype=treatment))
p3<-p2+scale_x_continuous(name="Time(weeks)", breaks = seq(0,8,2))
p4<-p3+scale_y_continuous(name = "bprs")
p5<-p4+theme_bw()+theme(legend.position="right")
p6<-p5+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank())
p7<-p6+ggtitle("Fitted")
graph2<-p7
graph1;graph2
```

